# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/drenix/poky/meta \
  /home/drenix/poky/meta-poky \
  /home/drenix/poky/meta-yocto-bsp \
  /home/drenix/poky/meta-raspberrypi \
  /home/drenix/poky/meta-openembedded/meta-oe \
  /home/drenix/poky/meta-openembedded/meta-python \
  /home/drenix/poky/meta-openembedded/meta-networking \
  /home/drenix/poky/raspiproyecto/meta-connectRasperry-to-internet \
  "
